name: LiveMarket
version: 1.4.2
main: me.livemarket.LiveMarketPlugin
api-version: 1.21
depend: [Vault]

commands:
  lmupdate:
    description: Force market update
    permission: livemarket.admin
  shop:
    description: Open market GUI
    usage: /shop
    permission: livemarket.shop.open
  price:
    description: Show current item price
    usage: /price <material>
    permission: livemarket.price
permissions:
  livemarket.shop.open:
    default: true
  livemarket.price:
    default: true
  livemarket.buy:
    default: true
  livemarket.sell:
    default: true
  livemarket.auction:
    default: true

  livemarket.category.armor:
    default: true
  livemarket.category.food:
    default: true
  livemarket.category.tools:
    default: true
  livemarket.category.ores:
    default: true
  livemarket.category.blocks:
    default: true
  livemarket.category.misc:
    default: true

  livemarket.admin:
    default: op
