name: LiveMarket
version: 1.5.4
main: me.livemarket.LiveMarketPlugin
api-version: 1.21
depend: [Vault]

commands:
  shop:
    description: Open market GUI
    usage: /shop
    permission: livemarket.shop.open
  shopedit:
    description: Open market editor GUI
    usage: /shopedit
    permission: livemarket.shop.edit
  lmupdate:
    description: Force market update
    usage: /lmupdate
    permission: livemarket.admin

permissions:
  livemarket.shop.open:
    default: true
  livemarket.shop.edit:
    default: op
  livemarket.admin:
    default: op
